fix for #220
alphazframework/framework pull request #311
Opened 2020-08-25 10:14 UTC by Lablnet

https://github.com/zestframework/Zest_Framework/issues/220

2020-08-25 13:15 UTC, peter279k requested changes
These classes seems to be done and my recommendations are as follows:

- Each archive classes should have their unit tests and it can make their behaviors verified and reliable.
- The StyleCI has been failed to check on the latest commit and it should be fixed.

2020-11-25 10:21 UTC, lablnet commented
@Maikuolan tests pass in `gh actions`

2020-11-25 10:30 UTC, Maikuolan approved these changes
LGTM. :-)

2020-11-26 05:21 UTC, peter279k commented
coding style [error ](https://github.styleci.io/analyses/yv0QnN?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)should be concerned.

2020-11-26 05:24 UTC, peter279k commented on src/Archive/Archive.php
> +    public function setAdapter($adapter)
To be consistency, it should add the native type hint:

```PHP
public function setAdapter($adapter): self
```

2020-11-26 07:57 UTC, lablnet commented
> coding style [error ](https://github.styleci.io/analyses/yv0QnN?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)should be concerned.

there is no such error, its giving that in other file which is out of scope in sense of current PR

2020-11-26 08:01 UTC, peter279k commented
> > coding style [error ](https://github.styleci.io/analyses/yv0QnN?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)should be concerned.
> 
> there is no such error, its giving that in other file which is out of scope in sense of current PR

Right. Without coding style error, I think it should be good to merge this PR.

2020-11-26 08:24 UTC, merged